-- CreateTable
CREATE TABLE "USER" (
    "id" SERIAL NOT NULL,
    "name" TEXT,
    "phone_number" TEXT,
    "email" TEXT,
    "password" TEXT,
    "image" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER_ROLES" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER,
    "roleId" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "USER_ROLES_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PRODUCT" (
    "id" SERIAL NOT NULL,
    "image" TEXT,
    "name" TEXT,
    "price" INTEGER,
    "category" TEXT,
    "subcategory" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PRODUCT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ORDER_DETAIL" (
    "id" SERIAL NOT NULL,
    "price" INTEGER,
    "status" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "image" TEXT,
    "detail_cancel" TEXT,
    "user_id" INTEGER DEFAULT 1,

    CONSTRAINT "ORDER_DETAIL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ORDER_ITEMS" (
    "id" SERIAL NOT NULL,
    "orderdetail_id" INTEGER,
    "user_id" INTEGER,
    "product_id" INTEGER NOT NULL,
    "sweetness_level" INTEGER,
    "quantity" INTEGER,
    "price" INTEGER,
    "note" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ORDER_ITEMS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "POINTS" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "earned_points" INTEGER NOT NULL DEFAULT 0,
    "used_points" INTEGER NOT NULL DEFAULT 0,
    "order_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "POINTS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "POINTS_REDEMPTION" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "redeemed_points" INTEGER NOT NULL,
    "discount" DOUBLE PRECISION NOT NULL,
    "order_id" INTEGER,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT DEFAULT 'NOT_USE',

    CONSTRAINT "POINTS_REDEMPTION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_email_key" ON "USER"("email");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_name_key" ON "ROLES"("name");

-- AddForeignKey
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "ROLES"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_orderdetail_id_fkey" FOREIGN KEY ("orderdetail_id") REFERENCES "ORDER_DETAIL"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "PRODUCT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POINTS" ADD CONSTRAINT "POINTS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POINTS" ADD CONSTRAINT "POINTS_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "ORDER_DETAIL"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POINTS_REDEMPTION" ADD CONSTRAINT "POINTS_REDEMPTION_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "POINTS_REDEMPTION" ADD CONSTRAINT "POINTS_REDEMPTION_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "ORDER_DETAIL"("id") ON DELETE SET NULL ON UPDATE CASCADE;
