-- DropForeignKey
ALTER TABLE "ORDER_ITEMS" DROP CONSTRAINT "ORDER_ITEMS_product_id_fkey";

-- AddForeignKey
ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "PRODUCT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
